### ISSUE TITLE
Code crashes SSBB on Wii U

### ISSUE THREAD

**Issue by danielgerous** [wilm0x42/wii-gc-adapter-inject#1]
Hi thanks for making this tool!

I tried compiling your code, but ran into a number of re-declaration errors. I removed the declarations that already existed in my version of libogc, and was successfully able to compile. 

However, upon trying to launch this code with gecko on a NTSC-U Brawl disc and Wii U with Gecko I just get a black screen.

This is the text file I get that accompanies the gct file:
[wii-gc-adapter-gct.txt](https://github.com/wilm0x42/wii-gc-adapter-inject/files/1795362/wii-gc-adapter-gct.txt)

Is this what you expect it to look like? If not, could you please post what it should look like?

**Comment by wilm0x42** [comment]
Hello!

That's odd... Can you provide the output of `make` in the un-edited repo?
What revision of libogc are you using?

I'm a little confused as to how you got that file. The part of the Makefile that would generate it has been commented out for quite some time... Also, there's shouldn't be a `.gct`; there *should* be a `.gpf`.

Regardless, the .txt seems to follow the structure I'd expect. The addresses in it look a little fishy, though.

Anyway, about your build environment...

* What OS are you on?
* *DID* you get a `.gpf` from the build?
* What files show up in the `build` folder?

If `build/wii-gc-adapter-inject.elf` is larger than around 20kB, then I suspect it's somehow linking against libogc by mistake.

EDIT:  [Here's](https://github.com/wilm0x42/wii-gc-adapter-inject/files/1797761/patch.zip) the `patch` folder I get on my computer, if you'd like to test that.

**Comment by danielgerous** [comment]
Thanks for sending me your patch and getting back to me. It works great!

Here's the output when I try a make:
[makelog1.txt](https://github.com/wilm0x42/wii-gc-adapter-inject/files/1798170/makelog1.txt)

and here's the output of make after your most recent change:
[makelog2.txt](https://github.com/wilm0x42/wii-gc-adapter-inject/files/1798215/makelog2.txt)


I got that .txt file because I didn't read closely enough that this is a .gpf patch and not a .gct patch, so I just ran createGCT in buildtools... so pay that no mind.

Here's the .gpf that's generated in your old build, I can't get it to create a .gpf in your latest build.
[patch.zip](https://github.com/wilm0x42/wii-gc-adapter-inject/files/1798184/patch.zip)

Here's what shows up in the build folder when I make your old build:
[screenshot.zip](https://github.com/wilm0x42/wii-gc-adapter-inject/files/1798225/screenshot.zip)

I'm on Ubuntu 16.04, with DevkitPPC r27 and libogc 1.8.15-1. What versions of DevkitPPC and libogc do you have? I'll try and match whatever you have.

build/wii-gc-adapter-inject.elf is 21.8kb for me.

**Comment by wilm0x42** [comment]
Glad to hear it's working! (Seriously, you're like the first person besides me to use this)

There's your problem: Your clone of the repository, in the failing build, is in a folder named `wii-gc-adapter-inject-master`, rather than `wii-gc-adapter-inject`. This isn't *supposed* to be required, but renaming it should solve your problem. (This kinda would warrant a bugfix, but it probably doesn't matter *that* much...) If I'm wrong, don't hesitate to re-open this issue. ;)

Btw, Ubuntu 16.04, DevkitPPC r27, libogc 1.8.15-1. My setup is identical.

**Comment by JacobM2** [comment]
Thanks for uploading your compiled patch above wilm0x42! Just a heads up, it looks like a bunch of people have been trying to get this working for the past few days!

https://www.reddit.com/r/WiiUHacks/comments/82toin/gamecube_controller_adapter_for_super_smash_bros/
https://gbatemp.net/threads/need-help-with-vwii-gc-adapter-for-project-m.498236/
https://www.reddit.com/r/SSBPM/comments/82v0pe/smash_bros_brawl_can_now_support_the_gamecube/
https://www.reddit.com/r/smashbros/comments/82uzrb/smash_bros_brawl_can_now_support_the_gamecube/
